### ISSUE TITLE
More robust fetching

### ISSUE THREAD

**Issue by codl** [codl/forget#13]
Right now fetching assumes that every post before the most recent known post has already been fetched. If there are no known posts then it will recurse until the remote service doesn't return any posts anymore but otherwise it will only go up to the most recent known posts.

Unfortunately this means there is a failure state where posts were fetched from the most recent post to an arbitrary post that isnt the oldest post. This doesn't happen usually but if a worker is killed or throws an unusual exception while fetching then this can happen.

Recursing as far as possible every time we fetch isn't feasible due to rate limits

I'm not sure how to fix this, maybe keep track of which time (or id?) ranges have been successfully fetched, and try to fetch whichever ones are missing?

**Comment by codl** [comment]
no. begone stale bot

**Comment by good-praxis** [comment]
The code isn't self-explanatory explorable, so I'll just ask you, as the expert here, instead.
How about two flags in the db per account. Both initalized as false, as well as one field capable of holding an extra post.

1. when we complete the fetching for that account without an exception / hitting the rate limit / catching the possible "no-more-posts exception" that you maybe implemented, we set the first flag to true. Let's call this one "historically-complete". If we hit an exception or a ratelimit, then we try again later, starting with the latest entry of that account in db (probably by timestamp?). The latest post from the "history", we will reference in another field. By ID or timestamp, doesn't really matter.

2. When we do a request with historically-complete set to true, we check the first entry. If we notice that there are new posts we set "recently-complete" to false. As long as that is false, it'll try to receive all posts from the most recent to the one we set as the end of "history".
Once that's done we set "recently-complete" to true and only check for the latest posts again.

All names are of course subject to change, it's just a rough idea on how this could work. You tell me if it actually _would_ work

**Comment by good-praxis** [comment]
Sounds pretty good, however I need to ask about the logistics of this now, just to validate this again.

1. **not historically complete** -> This works because accounts are initalized in this state, and we will always fetch them until we reach the end of the accounts history.

2. **historically complete, no end of batch** -> This state is activated once we have the entire history in the DB, and there is a new post. We then save the _first_(?), most recently posted post as the _end of batch_? If that's true, what happens when we hit the rate limit / an unexpected exception during this stage? Will it retry gathering the entire batch on next try? Or will it automatically go into stage 3. if it crashes? Also when you say `fetching recent posts` in this stage, you mean fetch `end of batch` -> oldest known post?

3. **end of batch is set** -> `posts older than the oldest known post that is more recent than the one we marked as the end of the batch`. If the end of the batch is the most recent post at the beginning of the batch we query, then what exactly are we fetching now? Do you mean the oldest known post _of the batch_? By `more recent`, do you mean "more recently queried" or "more recently posted"?

**Comment by codl** [comment]
> We then save the first(?), most recently posted post as the end of batch?

Yes. The most recently posted post that is already in the database. Not sure what you mean by first?

> What happens when we hit the rate limit / an unexpected exception during this stage?

Not much. The whole SQL transaction is rolled back, including setting the end of batch, so the next fetch job will begin in the exact same state and attempt the same thing.

> Also when you say "fetching recent posts" in this stage, you mean fetch end of batch -> oldest known post?

No, literally the 40 most recent posts on the remote service.

> If the end of the batch is the most recent post at the beginning of the batch we query, then what exactly are we fetching now? Do you mean the oldest known post of the batch?

Yes. "The oldest known post that is more recent than the end of the batch" is the oldest known post of the batch. I probably shoulda said that in the first place 😅

> By more recent, do you mean "more recently queried" or "more recently posted"?

Whenever I refer to a post's age or recentness, I mean according to the time it was posted.

There's clearly a misunderstanding here so I've written an example:

```
Say we've got an account on twitter we're monitoring.
The bars here represent the account's state on twitter and in forget's DB,
with █ dark areas representing ~40 posts, and ░ light areas no posts (yet).
(40 posts is how many we can fetch in one request, and each fetch job uses exactly one request)

The two start out already in sync (so, historically complete):

|████░░░░░ Twitter
|
|████░░░░░ Forget
|
+--------> Time

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
JOB 1

A fetch job begins.
The user has posted a lot since we last ran a fetch job, but we don't know that yet.

|███████░░ Twitter
|
|████░░░░░ Forget
|
+--------> Time

There is no end of batch yet, so we follow the 2nd scenario.
We set the end of batch to the most recent post we know:

|███████░░ Twitter
|
|████░░░░░ Forget
|   ◢◣ end of batch
+---------> Time

We send a request for posts from twitter, and store them:

|███████░░ Twitter
|      ▼
|████░░█░░ Forget
|   ◢◣ end of batch
+--------> Time

The job ends.

~~~~~~~~~~~~~~~~~~
JOB 2

When the next job begins, the user has posted more:

|█████████ Twitter
|
|████░░█░░ Forget
|   ◢◣ end of batch
+--------> Time

We have an end of batch marker, so we follow the 3rd scenario.
We fetch posts that are older than
the oldest post within posts that are younger than the end of batch

i.e. we are fetching posts older than the set of posts we fetched last job.

|█████████ Twitter
|     ▼
|████░██░░ Forget
|   ◢◣ end of batch
+--------> Time

None of the posts we fetched are, or are older than, the end of batch,
so we're done.

~~~~~~~~~~~~~~~~~~~~
JOB 3

The next job goes much the same:


|█████████ Twitter
|    ▼
|███████░░ Forget
|   ◢◣ end of batch
+--------> Time

Except this time we reach the end of the batch. So we unset it.


|█████████ Twitter
|    ▼
|███████░░ Forget
|             (no end of batch)
+--------> Time

And we're done for this job.
The next job will run similarly to the first one, etc.
```

Does this help?

Also I forgot to mention that we can, and often will, reach the end of the batch in the same job that we set it in (scenario 2), in which case we just unset it.

**Comment by codl** [comment]
boy am i glad i wrote all this now that i want to implement it
