### ISSUE TITLE
Error returning to forget after cancelling authorization

### ISSUE THREAD

**Issue by chrisfetz** [codl/forget#14]
After I click "log in with twitter" and get to the page that says "authorize codl.forget.fr to use your acccount?" and click cancel, there's a button that says "return to forget.codl.fr." I click it and it takes me to a page with this error:
"Bad Request

The browser (or proxy) sent a request that this server could not understand."

I really like forget and this isn't a big deal at all, but I figured I should mention it! 👍

**Comment by codl** [comment]
thank you very much for reporting this!
