### ISSUE TITLE
Can't login with Twitter

### ISSUE THREAD

**Issue by XenonFiber** [codl/forget#204]
"Sorry, something went wrong when logging you in with Twitter. Give it another shot, maybe?"

I've relogged and tried again in 3 different browsers.

(on https://forget.codl.fr/)

**Comment by codl** [comment]
Hmm, odd. Have you tried logging out of twitter first?

**Comment by codl** [comment]
Also: could you log in before or was this your first time logging in?

**Comment by XenonFiber** [comment]
Yeah, and I've logged in a couple times before.
