### ISSUE TITLE
not all posts are tracked, for some reason

### ISSUE THREAD

**Issue by kit-sunei** [codl/forget#220]
my account has 3,993 posts according to mastodon, but for some reason only about 1,500 are known by forget.codl.fr

i was surprised an issue didnt exist yet so im making one! it's maybe not easy to solve, but an explanation and maybe "attempt to find more" button would be a good idea? i don't know why it gets desynced like this, though

account is @dahl@monsterpit.net in case that helps

**Comment by codl** [comment]
this happens sometimes and i don't know why. #154 was supposed to help but it doesn't seem like it did

i've reset your account, that usually fixes it, let me know if it does

**Comment by coffeeboodev** [comment]
I'm also having this issue. 256 tweets, 200 known by Forget.

**Comment by codl** [comment]
@coffeeboodev if that is a twitter account, you can try uploading a tweet archive, otherwise please email me with your account name so i can reset it

**Comment by minego** [comment]
This is happening to me as well... I'm m@birb.site in case you want to look. Thanks.

**Comment by codl** [comment]
Closing this for now. See #589 if you run into this.
