### ISSUE TITLE
clarify that "favourites" actually means "self-favourites" only

### ISSUE THREAD

**Issue by trwnh** [codl/forget#325]
testing with https://botsin.space/@trwnh_ebooks and the following settings:

- Age: Posts that are over [1 days] old and are not one of your [100] most recent posts
- Favourited: Keep [favourited posts]
- Media: Keep [neither]
- Keep direct messages [Yes]
- Expiry: Every [1 minutes]

### expected behavior
any post with at least 1 favourite is kept

### actual behavior
posts are deleted only according to age, regardless of fave count

### ???
maybe it's misinterpretation and only *self* favs are counted? in which case that should be made more clear, because i would not have enabled deletion if i'd known i would have to log into the bot account rather than being able to control it "remotely". or maybe it's not misinterpretation and it's a bug

**Comment by codl** [comment]
yes, it is "self favs" only

**Comment by codl** [comment]
at one point I had it say "Keep [posts that I have favourited]" but it made an already clumsy UI clumsier. I'd welcome suggestions for clearer wording

**Comment by trwnh** [comment]
"self-favourited"?
