### ISSUE TITLE
Quick switch between accounts

### ISSUE THREAD

**Issue by codl** [codl/forget#33]
allow users to be logged into >1 account at once and switch between them

**Comment by codl** [comment]
I don't think this is necessary anymore since the mastodon buttons on the front page remember which instances you use.

**Comment by bitspace-thor** [comment]
As far as I can tell, you still can't leave it running on multiple instances at once, though. Those buttons are only accessible if you log out, and I assume it doesn't run if you're logged out... or does it? I don't even know if it runs when you leave the page...

**Comment by codl** [comment]
it does keep running if you log out or leave the page

**Comment by codl** [comment]
which means, yes, you can leave it running on multiple instances already
