### ISSUE TITLE
Mastodon not deleting

### ISSUE THREAD

**Issue by LiamDawe** [codl/forget#392]
Hi, I have my account with Forget setup with Mastodon and it started working great, however now it seems to be stuck with no messaging to indicate why.

> Last delete 40 hours ago. Next delete anytime now...

That's all I see.

Any other info needed, let me know.

**Comment by MaiaDereva** [comment]
Hello, same here:

_Last delete 5 days ago. Next delete anytime now..
Currently keeping track of 198 of your posts, roughly 148 of which currently match your expiration rules._

Any information?

**Comment by ataraxia937** [comment]
I'm also seeing the problem with Pleroma.

**Comment by codl** [comment]
Sorry about the delay. A queue had filled up. Please check if it is working for you now.

**Comment by MaiaDereva** [comment]
Thanks a lot, everything seems to be OK now.
Is there another way than Liberapay to support your work?

**Comment by codl** [comment]
Not at the moment, but spreading the word always helps 😀
