### ISSUE TITLE
No posts detected

### ISSUE THREAD

**Issue by MicaNevermind** [codl/forget#396]
forget is not detecting any toots that match my filters, even though I have 1,6k posts most of them follower only.
"Currently keeping track of 0 of your posts, roughly 0 of which currently match your expiration rules."
using a mastodon instance with ~20 people on it.

**Comment by codl** [comment]
It's possible that this is related to #392, would you check if it works for you now? If not, would you give me your full handle `name@instance`?

**Comment by MicaNevermind** [comment]
Detects 160 toots of my 1,6k now and started to delete. Thank you for helping!

**Comment by codl** [comment]
Glad I could help 😊
