### ISSUE TITLE
Question: Favorite feature?

### ISSUE THREAD

**Issue by 96312** [codl/forget#480]
Hi, I've just stumbled upon this tool. Using it on twitter, does the favorite feature mean the tweets I've liked (on there) will be whitelisted and not deleted? Is that how it is supposed to work? Or is there a way to favorite tweets that I haven't discovered.

Anyways, thanks for this tool its really well done!

**Comment by codl** [comment]
yes, it means tweets you've liked

**Comment by 96312** [comment]
Okay, thanks.
