### ISSUE TITLE
no deletion is happening

### ISSUE THREAD

**Issue by dhuschde** [codl/forget#523]
Good Day,
Yesterday, I set up Forget for my Twitter Account. But it only deleted one Tweet and nothing more. And this since 17 hours. I set it up to delete every 30 minutes.

![My Settings](https://user-images.githubusercontent.com/85834680/131877918-775bf669-1f85-421a-8172-72a6b4502c5c.png)

**Comment by dhuschde** [comment]
It's working again.

Reason for not working:
![IMG_20210902_195551](https://user-images.githubusercontent.com/85834680/131893532-b9068e48-78cd-45da-81a5-8dc72fc38a7b.jpg)

**Comment by codl** [comment]
#398
