### ISSUE TITLE
Stuck again?

### ISSUE THREAD

**Issue by quat1024** [codl/forget#533]
All my accounts are saying "last delete 2 days ago, next delete any time now"

**Comment by jncosideout** [comment]
Same here. It shows it is tracking my total posts, and shows my filters working, but deletion is not happening when enabled.

**Comment by codl** [comment]
Hi, is this still happening?

**Comment by quat1024** [comment]
Doesn't appear to be 👀

**Comment by codl** [comment]
Closing this, then.
