### ISSUE TITLE
https://forget.codl.fr/ Down?

### ISSUE THREAD

**Issue by DiogoToraci** [codl/forget#539]
Hello, I hope you are doing well.

The site appears with a error:

502 Bad Gateway
Nginx /1.21.1

Best regards

**Comment by codl** [comment]
It's back, sorry for the trouble. I've disabled every account as a precaution. Just log in and click enable to turn it back on.

**Comment by DC7IA** [comment]
The message says "November 11", but today is 9.

**Comment by codl** [comment]
whoops

**Comment by codl** [comment]
fixed, thanks for the tip
it actually came back up on the 7th, i didn't remember to update this issue
