### ISSUE TITLE
support full twitter archive format

### ISSUE THREAD

**Issue by codl** [codl/forget#64]
reported by `rrix@cybre.space` <https://cybre.space/@rrix/100591445673683791>

> hey, it looks like the Twitter archive format changed at some point that makes it not work with Forget. there's no longer a data/js/tweets dir with monthly files, just a big jsonp file (67mib in my case) in the root of the zip

**Comment by codl** [comment]
?? i just requested a twitter archive and it still has /data/js/tweets. no big jsonp file at the root either. maybe this is some kinda A/B test?

@rrix can you provide an example archive? or more details about the format of the file & its filename?

**Comment by rrix** [comment]
Hey sorry about the delay, I finally found a browser session that was logged in to Github.

The file is a "little" large, I'll upload a version of it with media files dropped out of it to my nextcloud and DM you a link to it through the fediverse.

**Comment by codl** [comment]
ok i get it now. it's not a new format, it's a different archive. it's the full account archive you get from <https://twitter.com/settings/your_twitter_data> instead of the tweet archive you get from <https://twitter.com/settings/account#tweet_export>

they *could* be supported but it would require extracting the zip in the browser and parsing it there, cos we cant reasonably upload gigabytes of images and videos just to get a few thousand tweet IDs. I'm not going to do that. but if someone's up to the task I'd be happy to help and to merge it in

what i *will* do is document it, link to the right page, and pop a warning before uploading if the archive is more than, say, 25 MB. mine reaches 6.3 MB with 30k ish tweets so i figure that's a safe value

**Comment by codl** [comment]
it sure did take me a whole month to figure that out huh 😅

**Comment by rrix** [comment]
Oh wow, I had no idea there were two different things there. I'll upload the archive you're expecting, thanks for the pointer and investigating!

**Comment by codl** [comment]
Hi all. Sorry for taking so long. I intend to get this done by the end of the month.
