### ISSUE TITLE
keep posts based on popularity (likes & boosts)

### ISSUE THREAD

**Issue by codl** [codl/forget#7]
As suggested by alyx@&zwnj;witches.town ~~[[1]](https://witches.town/users/alyx/updates/663391)~~:

> a good expiration rule might be X number of boosts/likes can stay

**Comment by gevta** [comment]
slow exponential growth seems to be a better policy than the linear interactions/time

**Comment by Antoine-Derouin** [comment]
Hello,
I am very interested in keeping only Toot's that have received boost, stars and/or answers!
(after an expired publication deadline.)

**Comment by Antoine-Derouin** [comment]
Hello,
I am very interested in keeping only Toot's that have received boost, stars and/or answers!
(after an expired publication deadline.)

**Comment by codl** [comment]
Hi all, this issue has been haunting me for the year and a half that it has been open. Honestly, I don't want to work on it because I'm worried that it contributes to the popularity contest spirit that social media often gets into. I mean, posts being only worth keeping if enough people like them? That sounds unhealthy to me, and I don't want my work to push that sort of idea

But I could be wrong and there may be uses for such a feature that I hadn't thought of. If you want this feature, I'd like to hear about your use case
